plugins { id 'com.android.application' }

android {
    namespace 'com.malikit.v8'
    compileSdk 36
    defaultConfig {
        applicationId 'com.malikit.v8'
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName '8.0.0'
    }
    buildTypes { release { minifyEnabled false } }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
